name: Tests

on:
  - push
  - pull_request

env:
  'default-python-version': '3.10'

jobs:
  tests:
    name: python ${{ matrix.python-version }}
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install hatch
      run: |
        python -m pip install --upgrade pip
        pip install hatch

    - run: hatch run cov
    - run: hatch run flake8
    - run: hatch run mypy hatch_zipped_directory
